apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: redis
    spec:
      containers:
      -
        image: redis
        name: redis
        ports:
        - containerPort: 6379
        imagePullPolicy: Always
      restartPolicy: Always