apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-app-example
  name: users-api
spec:
  ports:
  - port: 8083
    name: web
    protocol: TCP
  - port: 8000
    name: debug
    protocol: TCP
  selector:
    service: users-api